add auto ssh and try replace salt in wp-config.
josephhernandez209/wordpress pull request #1
Opened 2023-11-22 19:11 UTC by joemama597

2024-01-22 18:11 UTC, josephhernandez209 commented
add https://wp-cli.org/ 
to add the woo plugin automatically

2024-01-22 20:19 UTC, stephenlauck requested changes

2024-01-22 20:19 UTC, stephenlauck commented on wordpress.sh
> +$(curl https://api.wordpress.org/secret-key/1.1/salt/)
We should just get the RAW output of the URL and put it here for now.

2024-01-25 02:03 UTC, stephenlauck approved these changes

2024-01-29 17:49 UTC, merged